### ISSUE TITLE
After upgrade to 1.5.2:  Make sure the Client Side Encryption(CSE) script did encrypt the Credit Card details

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/magento#533]
Grund
Missing the encrypted data value. Make sure the Client Side Encryption(CSE) script did encrypt the Credit Card details

How can we make this sure?

**Comment by rikterbeek** [comment]
Hi Shirtsofholl,

The calls to the script and the script itself has changes. I think you have some magento or browser cache that is causing this problem could you flush both and check if this resolve your issues ?

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
thanks I just called support seems a misconfigured PGP? (but dont
understand why since just upgraded from 5.1 to 5.2)

This is our setting now: but still it does not work

I would expect when setting this setting to enable = NO

that it should work

[image: Inline afbeelding 1]




2016-02-24 10:14 GMT+01:00 Rik ter Beek <notifications@github.com>:

**Comment by rikterbeek** [comment]
Hi Shirtsofholl,

I do not understand what you mean. Support has mailed you to verify the WS username and password and public key. If you have still questions answer this mail or send a new mail to support@adyen.com

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Shirtsofholl,

I heard from my colleague that it is solved so i am closing this issue.

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
We are still seeing this error .... 3 errors this morning

But the last days we also had some succesfull payments .... so what is the
cause?

all cache was cleared, reset, had contact with helpdesk .... compared keys,
cleared cache again

This seems to be related to some other problem ...




Wij maken het graag voor je in orde.

met groeten, Mark


_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | https://shirtsofholland.com

[image: ShirtsofHolland - dé specialist in Oranje kleding]
<http://shirtsofholland.com/>

2016-02-24 13:22 GMT+01:00 Rik ter Beek <notifications@github.com>:
